#!/usr/bin/env ruby

require_relative "../lib/aide"

Aide.load_scripts!

script = Aide::Script.scripts[Aide.script_name]

if ARGV.empty?
  Aide::Scripts::Help.run
  exit 0
end

if script
  script.run(*Aide.script_args)
else
  puts "Script '#{script}' not recognized"
  puts

  Aide::Scripts::Help.run

  exit 1
end
